# Spring Boot configuration
spring:
  profiles:
    active: google
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql:reciepts_test
    username: postgres
    password: 
    pool-size: 2    
# Spring Security configuration
security:
  oauth2:
    client:
      clientId: 670079420791-lipilrp5qurbtfgi7laepscr00utkit0.apps.googleusercontent.com
      clientSecret: oiQFxf4UycoySSBkig7cSJLx
      accessTokenUri: https://www.googleapis.com/oauth2/v4/token
      userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
      clientAuthenticationScheme: form
      scope: email
    resource:
      userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo
      preferTokenInfo: true
# Server configuration
server:
  port: 8181